### ISSUE TITLE
sheikh infinite text

### ISSUE THREAD

**Issue by trieaade** [AmazingAmpharos/OoT-Randomizer#157]
the first time you pull the mastersword after the cutscene is done you talk to sheikh that conversation box repeats the same thing endlessly

**Comment by TopHatMan** [comment]
Somehow your game did not get its flags overwritten and shiekah is there. So you need to check your python.

**Comment by AmazingAmpharos** [comment]
This could also happen if you used a non-randomizer save file with the randomizer. Some emulators transfer save files rather sloppily between anything that is considered OoT, and a non-randomizer save file will encounter this issue because the randomizer hard assumes that certain flags will be written on save file creation. It's also possible you are not using a new enough version of python; we have seen that before as well. Be sure you have version 3.6 or newer.
