### ISSUE TITLE
When A promp appears for chest with deku shield, game crashes.

### ISSUE THREAD

**Issue by CriusNyx** [AmazingAmpharos/OoT-Randomizer#188]
Two roms which I generated locked up when I approached a chest containing the Deku Shield. Glitch is reproducible as adult, and child.

Spoiler logs provided for both roms. One rom has Deku Shield in Training Grounds, other in Redead grave.

[OoT_R52RSBANBJBEAKAJAB_6OIZ1QZN21_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2568860/OoT_R52RSBANBJBEAKAJAB_6OIZ1QZN21_Spoiler.txt)
[OoT_R52RSBANBJBWAKAJED_H2IJIX8KJY_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2568861/OoT_R52RSBANBJBWAKAJED_H2IJIX8KJY_Spoiler.txt)

**Comment by CriusNyx** [comment]
This was bug was found running Mupen64Plus with Retroarch, but also happens when running Paralell64 with Retroarch.

**Comment by flagrama** [comment]
You didn't happen to download the first release of 3.0 did you? I believe it was released the day before the current release, so Oct 22nd instead of Oct 23rd. I know this was a known bug with that. If you redownload it from the release files and use the same settings string/seed can you see if you have the same issue still?

**Comment by CriusNyx** [comment]
I wasn't able to create a duplicate of that rom, but I did create a new rom using the python source code version, and was able to collect a deku shield from a chest.

Thank you for the assistance.
