### ISSUE TITLE
Can Water Temple be made unbeatable due to keys?

### ISSUE THREAD

**Issue by xathian** [AmazingAmpharos/OoT-Randomizer#207]
So my seed has been good so far. It's my first time doing a randomizer, really stumped me at some points but it's been super fun although I'm at a point here in terms of fully completing the Water temple. I have all the tools to carry on and even killed Morpha immediately since I already had the key (Boss keysanity, silver keys still left in the dungeons as usual) and the Iron Boots+Longshot. My issue is that I had access to the first Silver key in the dungeon and had 3 choices available to me where to use it, I used it on one door and that led to a dead end (Chest with rupees) and now I have 2 remaining accessible paths but both lead to chained doors, no more dungeon chests are accessible to me, they're all past the chained doors. I cannot get any more keys, in fact I can't even get far enough in the dungeon to change the water level, I can only access 3 rooms and the boss room. Now this may not even matter as I have the Medallion obtained and the remaining needed items to finish the game **might** be elsewhere but I have no way of knowing if an item I vitally need (right now that would be Saria's Song) is in one of those later chests.

So that's my question, if the randomizer puts me in a position where I can't progress to any more of the dungeons chests, does that mean that vital items are guaranteed to not be in there? I don't want to just move on and find out my seed is broken 20 hours from now. Maybe I'm missing something here but I've walked down every accessible path in the dungeon a good 2 dozen times now, I cannot find anything to do to progress.

Also I generated without a spoiler log as I was wanting to do this without cheating temptation.

**Comment by flagrama** [comment]
You can change the water level in Water Temple freely using some creative mechanic usage. You can obviously always drain the water level as usual from highest water level.

From there the other two water levels may require you to save and reset to return to the entrance.

To get the water level to the highest level without unlocking the doors to it you can use Hover Boots to run towards the plaque that does so. Aim more towards the left side, otherwise you'll likely not be able to maintain your grip and be pushed off.

To get the water level to the middle water level just jump from the entrance and aim for the middle level of the tower. Then light the torch with either Fire Arrows or Din's Fire. This will unbar the door that leads directly to the middle water level plaque.

Using these strategies you should be able to access many more chests that should lead you to more keys.

---
One other thing to take note of though, is if you turned off  "All Locations Reachable" yes, you can be locked out of stone dungeons and/or Water and Fire Temples.

**Comment by rlbond86** [comment]
> I cannot get any more keys, in fact I can't even get far enough in the dungeon to change the water level

You don't need a key to change the water level. You can lower the level with just the iron boots and you can raise it to mid-level with fire arrows or Din's fire. 

The dungeon is definitely possible, you are just missing a chest somewhere or need to come back with better equipment.

**Comment by xathian** [comment]
>Aim more towards the left side, otherwise you'll likely not be able to maintain your grip and be pushed off.

This was it, thank you. I needed the water raised and tried this many times but I always slipped off so I figured it was impossible, but aiming for the far left side let me climb up.
