### ISSUE TITLE
Stuck at Sheik in Temple of Time

### ISSUE THREAD

**Issue by misterhat** [AmazingAmpharos/OoT-Randomizer#213]
I unlocked the Song of Time, went to the Temple of Time and played it. The doors opened and I picked up the master sword and watched the cut scenes. After Link transforms, Sheik arrives and the dialogue gets stuck in an endless loop describing where the medallions are located. Pressing A or B just keeps progressing them infinitely.

**Comment by flagrama** [comment]
You likely had a vanilla save file before playing randomizer. This is likely only an issue with PJ64 as well since other emulators use the file name of the ROM to name the save files, while PJ64 uses the internal name. You'll have to go to your saves directory and delete the "THE LEGEND OF ZELDA" save file. **Deleting the in-game save file will not help**. You have to delete the whole SRAM save file. You'll also have to do this every time you update the randomizer just to be sure you get all of the patches that are applied the first time you run the ROM.

This is just another reason PJ64 is not recommended at all.

If this is not the issue, I'm not sure of anything else that would cause this, but would like more information such as what emulator you are using.

**Comment by misterhat** [comment]
I'm using mupen64plus. I found `THE LEGEND OF ZELDA (unknown rom).sra` in the directory and removed it. mupen64plus is using `Legend of Zelda, The - Ocarina of Time (U) (V1.0) [!].sra` for the randomizer because I applied the subscreen delay hack from the official ROM, which brought the GoodName with it. Is there any way to recover the save or should I just restart?

**Comment by flagrama** [comment]
There should not be any need to use the hack if you are using GLideN64 as it already fixes the root issue.

There isn't really any way to recover the save as of currently. You'll have to restart.

**Comment by misterhat** [comment]
I tried Glide64, Glide64mk2 and Rice and they all take a long time to open the subscreen. Checking the mupen64plus INI file shows that it automatically applies a gameshark code to the official ROM md5sums. There is also glitches with the font on rupees/skulltulas and timers.

**Comment by flagrama** [comment]
Yes, GLideN64 is a different plugin than all three of those. Specifically this mupen version should have the plugin: https://m64p.github.io/

**Comment by misterhat** [comment]
Alright, compiled GlideN64. Looks much better now, thanks so much!

EDIT: Wish I knew about this plugin earlier. Every game renders beautifully now.
