### ISSUE TITLE
Problem with tunic requirement

### ISSUE THREAD

**Issue by nature1996** [AmazingAmpharos/OoT-Randomizer#218]
Settings (T62CA8JZGKBWAKAAEB) ; Seed: LLD9KP8HLA

I'm curently in the situation where I need to buy one of the tunic (both actually looking at the spoiler log) if I want to continue. The goron tunic is in the fire temple, and the zora tunic is in the water temple. normaly, the "fewer tunic requirement" option is off, so as I understand it this shouldn't happen, especially not twice, or if not maybe it should be added the the only normal requirement is the adult wallet in the description...

Or maybe yet again I misunderstood the whole thing, and activationg the option just allow the possibility to do what is listed whitout penality for the player (aka the timer), and in such case I would propose for the option to be moved in the "open" set of rules, or the 
"World" or "Remove Specific Location" set.

[OoT_T62CA8JZGKBWAKAAEB_LLD9KP8HLA_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2723128/OoT_T62CA8JZGKBWAKAAEB_LLD9KP8HLA_Spoiler.txt)

**Comment by rlbond86** [comment]
"Fewer Tunic Requirements" means that the player might be required to go into parts of the Fire and Water Temples without the appropriate tunic.

However, if you have the adult's wallet you can buy the red tunic and if you have the giant's wallet you can buy the blue tunic. You might be required to do that on any playthrough instead of getting the tunics from treasure chests. 

If you have "fewer tunic requirements", you might not have the bigger wallets by the time you have to go into those Temples.

**Comment by flagrama** [comment]
If you look at the playthrough you'll see that you are intended to purchase the tunics as rlbond said.

**Comment by nature1996** [comment]
My bad. Should maybe explicit the tooltip
