### ISSUE TITLE
Using the 'Hold Z after catching fish to receive adult fishing drop' bug results in getting an extra progressive scale (silver->golden->golden)

### ISSUE THREAD

**Issue by 0x0DEDC0DE** [AmazingAmpharos/OoT-Randomizer#39]
This one's easy to replicate, catch a record fish, hold Z, swim to counter, weigh fish, and presto you have the "wrong" drop.

I'm aware the randomizer's logic is primarily focused no major glitches style runs but I'd consider this a fairly minor glitch.

**Comment by AmazingAmpharos** [comment]
I'm not supporting item manipulation glitches (glitches that in any way glitchily manipulate your inventory which this 100% does). That being said, this is an open issue because I need to basically patch this vanilla bug out of the game, probably just by making the fixed scale into a recovery heart.

**Comment by 0x0DEDC0DE** [comment]
yeah I figured, it doesn't really break anything - it's just a bit wonky so I figured it's probably worth patching out since you've patched a few other vanilla things as well (the logic seems to work either way, although I had issues getting the piece of heart generated there after - this did not impact the run, the spoiler verified that it was a piece of heart like in vanilla... and it was in my second run too - is the child fishing item always a piece of heart or am I just unlucky?)


as a side note, the MM-style inventory breaks other glitches like equip swap to duplicate big poes (unless you're fine with overwriting din's fire) but this is probably on purpose since the logic's designed to be beatable glitchless - this is just an interesting side-effect I noticed (you can't equip swap over an empty slot or a grayed out slot since these are nonequippable).

**Comment by 0x0DEDC0DE** [comment]
Oh and an OoT bug that actually causes problems:

You can't cast the rod if you're swordless, the logic didn't give me a sword as child link until pretty far in - this makes getting child link fishing reward slightly tricky if the kokiri sword is in a silly place like... adult spirit temple, or shadow temple perhaps.

I'm not sure if you could reasonably patch that or if this is known and the logic considers it. (If the logic does NOT consider it AND if the child reward is randomized then in principle it could be unobtainable by being the kokiri sword since you'd need the kokiri sword to fish... to get the kokiri sword)

**Comment by CMuncey** [comment]
The logic does consider the need for a sword for child fishing

**Comment by AmazingAmpharos** [comment]
So upon further review, the new override system actually does cause this glitch to work "correctly" and give the shuffled item, and since that kinda took care of itself, I see no need to go in and heavy-handed force people not to use the vanilla bug as I was originally considering. Also the logic is aware/accounts for the sword req for child fishing. I think we can close this one.
