### ISSUE TITLE
Zelda's Lullaby unobtainable and certain key items randomize which can break the game.

### ISSUE THREAD

**Issue by TripleTomTv** [AmazingAmpharos/OoT-Randomizer#56]
So i've got a very interesting seed and i almost got everything i need to face ganondorf. The only problem is due to the game never giving me Zelda's Lullaby, i can't finish the game, especially because i'm not an OOT speedrunner so i can't use many glitches to get the job done regardless.
I've come to a situation where i have every song except Sarias Song and Zelda's lullaby learned, but i need to get the Zora Sapphire from the water temple which requires Zelda's lullaby to get through the dungeon.
I'm only missing the 3rd sacred stone to trigger the cutscene where you encounter ganondorf as young link and later get the ocarina of time and learn a new song. Since i don't have Zelda's Lullaby i also can't get to the royal tomb where you normally get the Sun Song, so i'm completely out of luck and can't finish the game sadly.
Also another bug that pretty much broke the shadow temple: There's that one room with one large burning skull where you need to throw a bomb in, when it explodes it drops a key item which you can pick up from the ground. This key item is randomized and therefore you can't get further into the dungeon since you need a key to get further. This issue affects all key items which you can pick up from the ground.
I could ignore the fact that i would need Zelda's lullaby if i could get through the shadow temple and just take the last medallion with me and face ganon but oh well... not possible. :(

**Comment by AmazingAmpharos** [comment]
Are you sure you can't finish Water Temple without Lullaby? Lullaby can be behind Water Temple as long as the Boss Key is in either the vanilla Map chest or the vanilla Compass chest. No real tricks are needed; you just don't ever change the water level and just explore the paths you can with the water level always at the highest. That gets you Lullaby and solves most of your other problems.

The Shadow Temple small key should be just in some other chest. There should still be the same total number of small keys as before; it's not really a problem for this key to be randomized any more than all the other keys. In Shadow Temple it's pretty easy to miss a chest. In the room with the invisible spinning blade, there's an invisible chest next to the visible one. In the room with the falling spike ceiling, there are three total chests. Most commonly, people who get stuck in Shadow Temple missed a chest in one of these spots.

I'll leave this open for a few days to give you a chance to confirm, but I don't think there are bugs here.

**Comment by TripleTomTv** [comment]
I am 100% certain that i did find all the chests i could for the shadow
temple, even the invisible ones and such.
As for the Water Temple i did the same, i opened and picked up everything i
could, but no luck sadly.
I didn't enable the spoiler log because i thought it would show all the
randomized items as soon as the process finished, now i can't it look up
because enabling the spoiler log changes the item layouts too.
Would it still help if i send you the name of my patched rom? I'm unsure if
there are all the informations you need for recreating the same patched
rom, but i'm currently out of my home and can't access my computer, so that
will have to wait a little.
I can send it tomorrow though if you want. (Hopefully)

AmazingAmpharos <notifications@github.com> schrieb am Di., 10. Juli 2018,
23:10:

**Comment by AmazingAmpharos** [comment]
Sorry I didn't see this for months. At this point, it seems unlikely offering help to find things would be meaningful, but indeed it's very easy to make mistakes in Shadow Temple or not to find both available chests in Water without Lullaby (the Compass chest in particular I think trips people up since the passage leading to it isn't actually at the bottom).

**Comment by Just-a-good-programmer** [comment]
So... I have an issue where I need the Gerudo membership card to get into jabu jabu (entrances are randomized), so I can get Zeldas lullaby. The problem is, that the membership card is located in the boss key chest of shadow temple, which can't be reached without the lullaby, at least as far as I know. Any ideas on how to bypass the gate of gerudo fortress (the one leading to gerudo training grounds, not the gate leading to haunted wastelands) or the boat to the shadow temple, without going directly to the boss room? Glitches are known territory for me, so no problems there... I already had to use my boomerang and hookshot as ocarina to get the ocarina in the same seed, so glitches are necessary to beat it.
