### ISSUE TITLE
[Suggestion] Add Dump Checksum to Instructions

### ISSUE THREAD

**Issue by raekuul** [AmazingAmpharos/OoT-Randomizer#60]
Like how the Link to the Past randomizer has the checksum for the correct game dump in it, can the instructions for the OoT Randomizer have the checksum for the correct game dump?

**Comment by AmazingAmpharos** [comment]
I'm not really sure what outputting the checksum would do (the compressor takes care of it on the fly, shouldn't matter to the user). If you mean the desired input checksum, it doesn't seem like the kind of information most users would find helpful, and 1.0's checksum is public knowledge out there somewhere anyway (and the types of people who really need to use a checksum can quickly just look in a hex editor since all N64 ROMs store their checksum very early in the ROM).
