### ISSUE TITLE
[Feature Request] Fetch Quest items not randomized to important items

### ISSUE THREAD

**Issue by tommaniacal** [AmazingAmpharos/OoT-Randomizer#91]
Since this randomizer's features are optimized for speedrunning (like the removal of cutscenes, dampe always digging the heartpiece on the first try, etc) , I think it would be great to remove the necessity of Gold Skulltula collecting, and Big Poe hunting. It's a pain when the reward for 50 Gold Skulltulas is the Letter in a Bottle, and the reward for 10 Big Poes is the Iron Boots (both have happened to me, it sucks). It stops progression, which isn't fun for anyone. I don't know if this is possible, but I thought I'd ask :]

**Comment by ChrisMuncey** [comment]
There's an option in TestRunner's fork to disable many of those annoying side quests, or shorten some of them. For example, you can set an option so that big poes will only require 1 big poe instead of 10. I'm not sure if all of those options will make it into 3.0, but you can use that fork for now if you want
